package feb;

public class Exception3 {
	
	
	public static void main(String[] args) {
		String s="mst";
   //valid value //20.00
		try {
	//	Double d=Double.parseDouble(s);//converting string 
		                          //into another datatype.
	//	Integer a=Integer.parseInt(s);
		//Number format exception
		//Run time 
		}
		//without catch block //no error bcz finally is there
		finally {
			System.out.println("I am in finally");
		}
		//Finally block will be executed 
		//no matter exception is coming or not
		
	}

}
